kubeconfigs:
- configpath: C:\Users\Administrator\.kube\cloudzcp-coinery-mainnet\kube-config2
  contexts: 
  - cloudzcp-coinery-mainnet/c5252e5802374426a78c74117315ab16/admin
  - cloudzcp-dep-dev/3d6b18b315544bcc8cdf94926c2d12c0/admin
